### ISSUE TITLE
Close database

### ISSUE THREAD

**Issue by kodiceone** [theianjohnson/expo-sqlite-eloquent-orm#1]
Hi,
first of all, awesome library. It solved in a moment long and exhausting search of an ORM for Expo easy to use and quick to adopt. Thank you!

Now, although it might be not very used, I've added on my side these two methods, and declared "db" as private.
I'm not sure it fit in your plan.

```typescript
  static async closeDatabase() {
    if (!this.db._closed)
      await this.db.closeAsync();
  }

  static async deleteDatabase(): Promise<boolean> {
    try {
      await this.closeDatabase();
      await this.db.deleteAsync();
      return true;
    } catch {
      return false;
    }
  }
```

**Comment by theianjohnson** [comment]
I'm actually needing this same functionality, let me get this added and tested and I'll get it shipped

**Comment by theianjohnson** [comment]
@kodiceone I added a Model.resetDatabase() method, see if that works for you. It works in the /example/App.js on Expo Go, but it throws a SQLite error in the iOS simulator when trying to re-migrate (but does then migrate fine if you reload) and haven't figured out how to fix that error yet
